version: '3'

services:
  frontend:
    build:
      context: ./weather-tracker/weather-tracker-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
      - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
      - VITE_API_URL=http://localhost:5001
    volumes:
      - ./weather-tracker/weather-tracker-frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: 
      context: ./weather-tracker/weather-backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - CORS_ORIGIN=http://localhost:5173
      - PORT=5001
    volumes:
      - ./weather-tracker/weather-backend:/app
      - ./weather-tracker/weather-backend/serviceAccountKey.json:/app/serviceAccountKey.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - backend

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-dashboard.json:/etc/grafana/provisioning/dashboards/weather-dashboard.json
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  alertmanager_data:
  grafana-storage: 